### ISSUE TITLE
Hyperlinks not working at all

### ISSUE THREAD

**Issue by Rabbia-Hassan** [Yan-Xia/Text2Loc#2]
Hello,
thank you for such interesting work.
However, these hyperlinks are not working , can you please fix them ?
![image](https://github.com/user-attachments/assets/9dce81d5-a9eb-4758-9cf0-2b9ee6fea43c)

![image](https://github.com/user-attachments/assets/20012014-2ccf-4ad6-9582-194210588747)

Thanks
I look foward to your response

**Comment by anslt** [comment]
The link works fine for me. Is that still a problem for you?

**Comment by anslt** [comment]
Please wait a little bit. The problem may be fixed tomorrow.

**Comment by dengshy** [comment]
> Please wait a little bit. The problem may be fixed tomorrow.

still 443

**Comment by Yan-Xia** [comment]
> > Please wait a little bit. The problem may be fixed tomorrow.
> 
> still 443

Hi! Sorry for that. The server of our chair is in maintenance, so the KITTI360Pose dataset and pre-trained pointnet model from [Text2Pos](https://github.com/mako443/Text2Pos-CVPR2022?tab=readme-ov-file) cannot be downloaded now.  We have uploaded the pre-trained pointnet model to[ Google Drive ](https://drive.google.com/file/d/1j2q67tfpVfIbJtC1gOWm7j8zNGhw5J9R/view?usp=drive_link) but still uploading the dataset to the cloud due to its big size.

**Comment by PT-10** [comment]
Has the KITTI360Pose dataset been uploaded elsewhere, from where it can be accessed?

**Comment by Yan-Xia** [comment]
Hi! I have uploaded the KITTI360Pose dataset to Google Drive. You can download them [here](https://drive.google.com/file/d/1JT6WALzntau7y_JwYdv5IKJRVPeGzaT0/view?usp=sharing)

**Comment by Yan-Xia** [comment]
The KITTI360Pose dataset and pre-trained model have been downloaded to Google Drive. You can access them now.
